apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: evalbench-namespace
  name: evalbench-eval-server-deploy
  labels:
    app: evalbench-eval-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evalbench-eval-server
  template:
    metadata:
      labels:
        app: evalbench-eval-server
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      securityContext:
        fsGroup: 0
      serviceAccountName: evalbench-ksa
      containers:
      - image: us-central1-docker.pkg.dev/cloud-db-nl2sql/evalbench/eval_server:latest
        env:
        - name: EVAL_DB_PASSWORD
          value: pantheon
        - name: UV_CACHE_DIR
          value: /tmp/uv-cache
        - name: EVAL_GCP_PROJECT_ID
          value: cloud-db-nl2sql
        - name: GOOGLE_CLOUD_PROJECT
          value: cloud-db-nl2sql
        - name: EVAL_GCP_PROJECT_REGION
          value: us-central1
        imagePullPolicy: Always
        name: evalbench-eval
        resources:
          requests:
            cpu: "20"
            memory: "80Gi"
          limits:
            cpu: "20"
            memory: "80Gi"
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          runAsUser: 0
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
        ports:
        - protocol: TCP
          containerPort: 50051
          name: grpc
        - protocol: TCP
          containerPort: 8000
          name: metrics
        - protocol: TCP
          containerPort: 3000
          name: ui
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /tmp_session_files
          name: gcs-fuse-csi-vol
        - mountPath: /tmp_sessions
          name: evalbench-ssd-vol
        - mountPath: /etc/evalbench-sa-key
          name: evalbench-sa-key-vol
          readOnly: true
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: gcs-fuse-csi-vol
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: evalbench-sessions-cloud-db-nl2sql
            mountOptions: "implicit-dirs,uid=0,gid=0"
      - name: evalbench-ssd-vol
        persistentVolumeClaim:
          claimName: evalbench-ssd-pvc
      - name: evalbench-sa-key-vol
        secret:
          secretName: evalbench-sa-key
          defaultMode: 0444
