import os
import subprocess
import sys
from absl import logging


def run_script(script_path: str, session_dir: str, label: str = "script") -> int:
    """Runs a shell script, capturing and logging all output to stdout and a file.

    Args:
        script_path: The full path to the shell script file.
        session_dir: The directory where log output should be written.
        label: A descriptive name for the script (e.g. 'setup') to use in the log filename.

    Returns:
        The return code of the process, or -1 if execution failed.
    """
    if not os.path.exists(script_path):
        logging.error(f"Cannot run script: '{script_path}' not found.")
        return -1

    # Ensure the session directory exists
    try:
        os.makedirs(session_dir, exist_ok=True)
    except Exception as e:
        logging.error(f"Failed to create session directory '{session_dir}': {e}")
        return -1

    log_file_path = os.path.join(session_dir, f"{label}_execution.log")

    logging.info(f"--- Executing {label} script: {script_path} ---")
    logging.info(f"--- Capturing output to: {log_file_path} ---")

    try:
        with open(log_file_path, "w", encoding="utf-8") as log_file:
            # Use bash explicitly to execute the shell script
            # Merge stderr into stdout using STDOUT so all outputs are chronologically interleaved
            process = subprocess.Popen(
                ["bash", script_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                env=os.environ.copy(),
                bufsize=1,  # line buffered
            )

            # Stream output live as it is generated by the subprocess
            if process.stdout:
                for line in process.stdout:
                    # Write line directly to sys.stdout stream so it appears in application logs
                    sys.stdout.write(line)
                    sys.stdout.flush()

                    # Save line to the target file in the session directory
                    log_file.write(line)
                    log_file.flush()

            process.wait()

            final_msg = f"\n--- {label} script finished with return code: {process.returncode} ---\n"
            sys.stdout.write(final_msg)
            sys.stdout.flush()
            log_file.write(final_msg)

            if process.returncode != 0:
                logging.error(f"{label} script execution failed with return code {process.returncode}")
            else:
                logging.info(f"{label} script execution completed successfully.")

            return process.returncode

    except Exception as e:
        error_msg = f"Exception encountered running {label} script: {str(e)}"
        logging.exception(error_msg)
        # Attempt fallback write to the log file if we had write permissions issues previously
        try:
            with open(log_file_path, "a", encoding="utf-8") as log_file:
                log_file.write(f"\nFATAL SYSTEM ERROR: {error_msg}\n")
        except Exception as fallback_err:
            logging.debug("Failed to record fatal error to fallback log: %s", fallback_err)
        return -1
